name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies and Start Flask App
        run: |
          pip install flask
          nohup python app.py > flask.log 2>&1 &  # Start Flask in the background
        env:
          FLASK_APP: app.py

      - name: Wait for Flask App to Start
        run: sleep 10  # Wait for the app to initialize

      - name: Ensure config file exists
        run: |
          ls -l $(pwd)/custom_config.conf

      - name: Ensure ZAP working directory exists
        run: |
          mkdir -p $(pwd)/zap_wrk
          sudo chmod -R 777 $(pwd)/zap_wrk  # 确保 Docker 可以写入

      - name: Run OWASP ZAP Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          sudo docker run --rm \
            -v $(pwd)/zap_wrk:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://host.docker.internal:5000 \
            -c /zap/wrk/custom_config.conf \
            -l WARN \
            -r /zap/wrk/zap_report.html \
            2>&1 | tee $(pwd)/zap_wrk/zap.log || true

      - name: Save ZAP logs
        if: always()
        run: cat /zap/wrk/zap.log

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: /zap/wrk/zap_report.html

