name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies and Start Flask App
        run: |
          pip install flask
          nohup python app.py &  # Start Flask in the background
        env:
          FLASK_APP: app.py

      - name: Wait for Flask App to Start
        run: sleep 10  # Wait for the app to initialize

      - name: Run OWASP ZAP Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \-t https://localhost:5000 -g gen.conf -r testreport.html
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4.6.1
        with:
          name: zap-security-report
          path: zap_report.html
